# Generated by Django 4.1.2 on 2022-10-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='address_type',
            field=models.CharField(choices=[('pickup_point', 'pickup_point'), ('drop_off_point', 'drop_off_point')], default='pickup_point', max_length=50),
        ),
    ]
